"use client";

import { useState } from "react";
import type { CaseInput, CaseRecord } from "@/lib/types";

const COURTS = ["Pengadilan Negeri Jakarta Pusat", "Pengadilan Negeri Surabaya", "Pengadilan Negeri Medan", "Pengadilan Negeri Bandung", "Pengadilan Negeri Semarang", "Pengadilan Negeri Makassar", "Pengadilan Negeri Denpasar", "Pengadilan Negeri Palembang", "Pengadilan Negeri Yogyakarta", "Pengadilan Negeri Malang"];
const CASE_TYPES = ["Pidana Umum", "Pidana Khusus - Narkotika", "Pidana Khusus - Korupsi"];
const empty: CaseInput = { nomor_perkara: "", nama_terdakwa: "", jenis_perkara: CASE_TYPES[0], pengadilan: COURTS[0], nama_jaksa: "", nama_hakim: "", tanggal_pembacaan: "", waktu_pembacaan: "", ruang_sidang: "", catatan: "" };

export default function CaseForm({ initial, onCancel, onSave, submitLabel = "Simpan" }: { initial?: Partial<CaseRecord>; onCancel: () => void; onSave: (form: CaseInput) => void; submitLabel?: string }) {
  const [form, setForm] = useState<CaseInput>({ ...empty, ...initial });
  const [errors, setErrors] = useState<Partial<Record<keyof CaseInput, string>>>({});
  const set = (key: keyof CaseInput) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const required: (keyof CaseInput)[] = ["nomor_perkara", "nama_terdakwa", "pengadilan", "nama_jaksa", "nama_hakim", "tanggal_pembacaan", "waktu_pembacaan", "ruang_sidang"];
  const submit = () => { const next: Partial<Record<keyof CaseInput, string>> = {}; required.forEach((key) => { if (!String(form[key] || "").trim()) next[key] = "Wajib diisi"; }); setErrors(next); if (!Object.keys(next).length) onSave(form); };
  const input = (key: keyof CaseInput) => `w-full border rounded px-3 py-2 text-sm text-gray-800 focus:outline-none focus:ring-2 focus:ring-[#1D4E89]/30 focus:border-[#1D4E89] ${errors[key] ? "border-red-400" : ""}`;
  const field = (label: string, key: keyof CaseInput, child: React.ReactNode) => <div><label className="block text-sm text-gray-700 mb-1.5">{label} <span className="text-red-500">*</span></label>{child}{errors[key] && <p className="text-xs text-red-600 mt-1">{errors[key]}</p>}</div>;
  return <div className="bg-white border rounded-md p-5 sm:p-6 space-y-5" style={{ borderColor: "#DFE3E8" }}><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{field("Nomor Perkara", "nomor_perkara", <input className={input("nomor_perkara")} value={form.nomor_perkara} onChange={set("nomor_perkara")} />)}{field("Nama Terdakwa", "nama_terdakwa", <input className={input("nama_terdakwa")} value={form.nama_terdakwa} onChange={set("nama_terdakwa")} />)}<div><label className="block text-sm text-gray-700 mb-1.5">Jenis Perkara</label><select className={input("jenis_perkara")} value={form.jenis_perkara} onChange={set("jenis_perkara")}>{CASE_TYPES.map((type) => <option key={type}>{type}</option>)}</select></div>{field("Pengadilan", "pengadilan", <select className={input("pengadilan")} value={form.pengadilan} onChange={set("pengadilan")}>{COURTS.map((court) => <option key={court}>{court}</option>)}</select>)}{field("Nama Jaksa", "nama_jaksa", <input className={input("nama_jaksa")} value={form.nama_jaksa} onChange={set("nama_jaksa")} />)}{field("Nama Hakim", "nama_hakim", <input className={input("nama_hakim")} value={form.nama_hakim} onChange={set("nama_hakim")} />)}{field("Tanggal Pembacaan", "tanggal_pembacaan", <input type="date" className={input("tanggal_pembacaan")} value={form.tanggal_pembacaan} onChange={set("tanggal_pembacaan")} />)}{field("Waktu Pembacaan", "waktu_pembacaan", <input type="time" className={input("waktu_pembacaan")} value={form.waktu_pembacaan} onChange={set("waktu_pembacaan")} />)}{field("Ruang Sidang", "ruang_sidang", <input className={input("ruang_sidang")} value={form.ruang_sidang} onChange={set("ruang_sidang")} />)}<div className="sm:col-span-2"><label className="block text-sm text-gray-700 mb-1.5">Catatan</label><textarea rows={3} className={input("catatan")} value={form.catatan ?? ""} onChange={set("catatan")} /></div></div><div className="flex items-center justify-end gap-2 pt-2 border-t" style={{ borderColor: "#DFE3E8" }}><button type="button" onClick={onCancel} className="px-4 py-2 rounded border text-sm text-gray-600" style={{ borderColor: "#DFE3E8" }}>Batal</button><button type="button" onClick={submit} className="px-4 py-2 rounded text-sm text-white bg-[#0B2545]">{submitLabel}</button></div></div>;
}

