"use client";

import { CheckCircle2, ChevronLeft, ChevronRight, Eye } from "lucide-react";
import type { CaseRecord } from "@/lib/types";
import StatusBadge from "@/components/StatusBadge";

const formatDate = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("id-ID", { day: "2-digit", month: "long", year: "numeric" }) : "-";

export default function CaseTable({ rows, page, setPage, pageSize, total, onView, onMark, canMark }: { rows: CaseRecord[]; page: number; setPage: React.Dispatch<React.SetStateAction<number>>; pageSize: number; total: number; onView: (id: string) => void; onMark: (id: string) => void; canMark: boolean }) {
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  return <div className="bg-white border rounded-md overflow-hidden" style={{ borderColor: "#DFE3E8" }}><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500 border-b bg-[#FAFBFC]" style={{ borderColor: "#DFE3E8" }}>{["No.", "No. Perkara", "Nama Terdakwa", "Tanggal Pembacaan", "Pengadilan", "Jaksa", "Status", "Aksi"].map((column) => <th key={column} className="px-4 py-3 font-medium whitespace-nowrap">{column}</th>)}</tr></thead><tbody>{rows.length === 0 && <tr><td colSpan={8} className="px-4 py-10 text-center text-gray-400">Tidak ada data yang cocok dengan filter.</td></tr>}{rows.map((item, index) => <tr key={item.id} className="border-b last:border-0 hover:bg-gray-50 cursor-pointer" style={{ borderColor: "#DFE3E8" }} onClick={() => onView(item.id)}><td className="px-4 py-3 text-gray-500">{(page - 1) * pageSize + index + 1}</td><td className="px-4 py-3 font-medium text-gray-800 whitespace-nowrap">{item.nomor_perkara}</td><td className="px-4 py-3 text-gray-700 whitespace-nowrap">{item.nama_terdakwa}</td><td className="px-4 py-3 text-gray-600 whitespace-nowrap">{formatDate(item.tanggal_pembacaan)}</td><td className="px-4 py-3 text-gray-600 whitespace-nowrap">{item.pengadilan}</td><td className="px-4 py-3 text-gray-600 whitespace-nowrap">{item.nama_jaksa}</td><td className="px-4 py-3"><StatusBadge status={item.status} size="sm" /></td><td className="px-4 py-3" onClick={(event) => event.stopPropagation()}><div className="flex items-center gap-2 whitespace-nowrap"><button onClick={() => onView(item.id)} className="inline-flex items-center gap-1 text-xs px-2.5 py-1.5 rounded border text-gray-600 hover:bg-gray-50" style={{ borderColor: "#DFE3E8" }}><Eye size={13} /> Detail</button>{canMark && item.status === "belum" && <button onClick={() => onMark(item.id)} className="inline-flex items-center gap-1 text-xs px-2.5 py-1.5 rounded text-white bg-[#15803D]"><CheckCircle2 size={13} /> Tandai</button>}</div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between px-4 py-3 border-t text-sm text-gray-500" style={{ borderColor: "#DFE3E8" }}><span>Menampilkan {rows.length ? (page - 1) * pageSize + 1 : 0}–{(page - 1) * pageSize + rows.length} dari {total} data</span><div className="flex items-center gap-1"><button disabled={page <= 1} onClick={() => setPage((current) => Math.max(1, current - 1))} className="p-1.5 rounded border disabled:opacity-40" style={{ borderColor: "#DFE3E8" }}><ChevronLeft size={15} /></button><span className="px-2">{page} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage((current) => Math.min(totalPages, current + 1))} className="p-1.5 rounded border disabled:opacity-40" style={{ borderColor: "#DFE3E8" }}><ChevronRight size={15} /></button></div></div></div>;
}
